//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryLog
    {
        public int DiaryLogId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DiaryLogDate { get; set; }
        public string DiaryLogItem { get; set; }
        public string DiaryLogContents { get; set; }
        public bool DiaryLogStatus { get; set; }
        public int DiaryLogHours { get; set; }
        public string DiaryLogSituation { get; set; }
        public string DiaryLogSolve { get; set; }
        public string CreateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
